# introduccion a NumPy
NumPy (Numerical python) es una libreria fundamental para la 
computacion cientifica y el analisis de datos
- Proporcionar arreglos de N dimenciones
- Implementa funciones matematicas sofisticadas
- Proporciona herramientas para integrar C/C++ y tabien Fortran
- Proporciona mecanismos para facilitar la realizacion de tareas relacionadas con algebra lineal o numeros aleatorios

# IMPORTACIONES

In [3]:
import numpy as np


## Arrays
Un array es una estructura de datos que consiste en una coleccion de elementos (valores o variables),
cada uno identiicado por al menos un indice
Un array se alamacena de modo que la posicion de cada elemento se pueda calcular a partir de su tupla indice mediante una formula matematica.

El tipo mas simple de un arreglo es un array lineal, o tambien llamado array unidimencional.

### En NumPy
* cada dimension se denomina axis
* el numero de dimenciones se denomina rank
* La lista de miensiones con su correspondiente longitud se denomina shape
* el numero total de elementos se denomina   size

In [8]:
# array cuyos valores son 0
a=np.zeros((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


# a es un array
- Con dos axis, el primer axis de llongitud 2 y el segundo de longiud 4
- Con un rank igual a 2
- con un shape igua a (2,4)
- con un size de 8


In [14]:
a.shape

(2, 4)

In [16]:
a.ndim


2

In [18]:
a.size


8

In [22]:
# 2 maricies de ceros
a=np.zeros((2,2,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [32]:
# 2 maricies de ceros
a=np.ones((3,2,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [34]:
# arrays cuyos valores son todos de un solo valor indicado como segundoa rgumento
a = np.full((3, 2, 4), 6)
print(a)

[[[6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]]]


In [36]:
# Crear un array de números aleatorios con forma (3, 2, 4)
a = np.random.random((3, 2, 4))
print(a)


[[[0.01714167 0.09332713 0.01762171 0.64845694]
  [0.56767206 0.2832618  0.44010817 0.75381099]]

 [[0.40037339 0.4600458  0.76277696 0.21330456]
  [0.06143329 0.03509044 0.84362763 0.6206718 ]]

 [[0.49254566 0.81630596 0.75526135 0.80604994]
  [0.4686707  0.34441471 0.52202263 0.32741429]]]


In [40]:
print (a[1]*a[2])

[[0.19720218 0.37553813 0.57609596 0.17193413]
 [0.02879198 0.01208566 0.44039271 0.20321682]]


In [42]:
# el resultado de un np.empty no es predecible
# inicializa los valores del array con lo que haya en memoria en ese momento
np.empty((2,3,3))

array([[[8.38036381e-312, 5.43472210e-322, 0.00000000e+000],
        [0.00000000e+000, 1.37961302e-306, 1.15998412e-028],
        [4.31603868e-080, 1.94919985e-153, 3.98450763e+252]],

       [[2.25566551e+137, 5.87769019e+135, 1.15874961e-028],
        [7.36321615e+223, 1.06239598e-153, 3.98472821e+252],
        [1.06244660e-153, 9.78750380e+199, 6.97843734e+252]]])

In [48]:
#Inicializamos l array utilizando un array de python
b=np.array([[1,2,3],[3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [50]:
b.shape

(2, 3)

In [54]:
# Creaccion de Un arreglo utlizando una funcion basada en rangos.
#quiere decir que le vamos a dar un minimo y un maximo y el numero de elemetos del array
print(np.linspace(0,6,10))

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


In [58]:
#Inicializar un arreglo con valores aleatorios
np.random.randn(2,3,4)

array([[[ 0.22260236, -0.42107075, -0.80052207,  1.39993236],
        [ 0.57578896, -0.16935796,  1.87289863,  0.92628109],
        [-0.72756341, -0.02932001, -2.04811322,  0.20346215]],

       [[-0.40119376,  0.4635352 , -0.40127473, -1.25847772],
        [ 0.39914859, -0.22876382,  0.70614627, -0.38148655],
        [-1.04856818, -1.15022779, -0.3652623 , -0.70842271]]])

In [60]:
#Inicializar un arreglo con valores aleatorios
np.random.rand(2,3,4)

array([[[0.50412439, 0.99844617, 0.69829412, 0.44933611],
        [0.50337033, 0.73944482, 0.81719568, 0.73349262],
        [0.98617691, 0.18763695, 0.59413951, 0.7406267 ]],

       [[0.56065261, 0.26191509, 0.16390394, 0.13442063],
        [0.10010425, 0.29015003, 0.55898102, 0.5471739 ],
        [0.58150171, 0.16104966, 0.17481504, 0.62408822]]])

In [6]:
#gerar una matriz de numeros randomicos y que me encuentre el numero mayor y menor de esa matriz
a=np.random.randint(1,20,size=(3,3))
mayor=np.max(a)
menor=np.min(a)
print(a)
print("el numero mayor es: ",mayor)
print("el numero menor es: ",menor)

[[ 1  6 12]
 [11 10 18]
 [19 18  5]]
el numero mayor es:  19
el numero menor es:  1
